# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-10 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='companies',
            name='province',
            field=models.CharField(default=b'Beijing', max_length=30),
        ),
        migrations.AlterField(
            model_name='companies',
            name='address',
            field=models.CharField(default=b'', max_length=256),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='companies',
            name='is_enabled',
            field=models.IntegerField(default=1),
        ),
    ]
