# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20180510_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('restaurant_id', models.IntegerField(default=0)),
                ('is_enabled', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'restaurant_relation',
            },
        ),
    ]
