# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-03 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_restaurantrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='image_url',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
