# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(db_index=True, default=0)),
                ('dish_id', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('is_canceled', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('total_price', models.FloatField(default=0.0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meal_orders',
            },
        ),
    ]
