# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-15 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mealorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'order_id',
            },
        ),
    ]
