# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-15 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealorders',
            name='is_canceled',
        ),
    ]
