# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-24 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180524_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealorders',
            name='time_range',
            field=models.IntegerField(default=0),
        ),
    ]
