# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-09 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180609_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealorders',
            name='order_data',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
