# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-09 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180609_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealorders',
            old_name='order_data',
            new_name='order_date',
        ),
    ]
