# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-24 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('is_enabled', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'restaurants',
            },
        ),
    ]
