# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_timerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='image',
        ),
        migrations.AddField(
            model_name='dishes',
            name='image_url',
            field=models.CharField(default=b'', max_length=256),
        ),
    ]
