# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-14 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20180514_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='restaurant_name',
            new_name='name',
        ),
    ]
