# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-05-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_auto_20180514_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='is_enabled',
            field=models.IntegerField(default=1),
        ),
    ]
